topics:
-
  name: local_navigation
  topic: local_vel
  timeout: 0.5
  priority: 50
#-
#  name: controller
#  topic: controller_vel
#  timeout: 0.5
#  priority: 100
#
#locks:
#-
#  name: emergency_stop
#  topic: emergency_stop
#  timeout: 10.0
#  priority: 255